golden_financing/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls import url

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url('', include('loan_calculator.urls')),
]

loan_calculator/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^loan_calculator/$', views.LoanCalculatorAPIView.as_view(), name='loan_calculator_api'),
    url(r'^(?P<pk>\d+)/$', views.LoanCalculatorView.as_view(), name='loan_calculator_url'),
    url(r'^', views.LoanCalculatorView.as_view(), name='loan_calculator_url'),
]

loan_calculator/models.py
from django.db import models
from model_utils import Choices
from phonenumber_field.modelfields import PhoneNumberField
from model_utils.models import TimeStampedModel


class CustomerInfo(TimeStampedModel):
    first_name = models.CharField(
        max_length=100,
    )
    middle_name = models.CharField(
        max_length=100,
        blank=True,
    )
    last_name = models.CharField(
        max_length=100,
    )
    name_suffix = models.CharField(
        max_length=50,
        blank=True,
    )
    email = models.EmailField(
        max_length=254,
    )
    phone_number = PhoneNumberField(
        max_length=50,
    )
    city = models.CharField(
        max_length=100,
    )
    province = models.CharField(
        max_length=100,
    )

    class Meta:
        unique_together = [(
            'first_name',
            'last_name',
            'email',
            'phone_number',
            'city',
            'province',
        )]


class LoanInquiry(TimeStampedModel):
    LOAN_TYPE_CHOICES = Choices(
        ('type_a', 'Type A'),
        ('type_b', 'Type B'),
    )
    customer_info = models.ForeignKey(
        'CustomerInfo',
        on_delete=models.CASCADE,
    )
    loan_type = models.CharField(
        max_length=254,
        choices=LOAN_TYPE_CHOICES,
    )
    principal_amount = models.DecimalField(
        decimal_places=2,
        max_digits=18,
    )
    monthly_amortization = models.DecimalField(
        decimal_places=2,
        max_digits=18,
    )
    total_interest = models.DecimalField(
        decimal_places=2,
        max_digits=18,
    )
    loan_term = models.PositiveIntegerField()
    total_sum_of_payments = models.DecimalField(
        decimal_places=2,
        max_digits=18,
    )
    first_loan_payment_date = models.DateField()
    loan_maturity_date = models.DateField()

loan_calculator/forms.py
from django import forms
from decimal import Decimal
from loan_calculator.models import LoanInquiry
from phonenumber_field.formfields import PhoneNumberField


class LoanInquiryForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100)
    middle_name = forms.CharField(max_length=100, required=False)
    last_name = forms.CharField(max_length=100)
    name_suffix = forms.CharField(max_length=50, required=False)
    email = forms.EmailField(max_length=100)
    phone_number = PhoneNumberField(
        error_messages = {'invalid': 'Enter a valid phone number (e.g. +639xxxxxxxxx)'},
    )
    city = forms.CharField(max_length=100)
    province = forms.CharField(max_length=100)

    LOAN_TERM_CHOICES = [(x, x) for x in range(3, 19)]
    loan_term = forms.ChoiceField(
        required=True,
        choices=LOAN_TERM_CHOICES,
    )

    class Meta:
        model = LoanInquiry
        fields = [
            'loan_type',
            'principal_amount',
            'monthly_amortization',
            'loan_term',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

        self.fields['loan_type'].label = 'Select your desired Loan Type'
        self.fields['first_name'].widget.attrs['placeholder'] = 'First Name (required)'
        self.fields['middle_name'].widget.attrs['placeholder'] = 'Middle Name (optional)'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Last Name (required)'
        self.fields['name_suffix'].widget.attrs['placeholder'] = 'Suffix (optional)'
        self.fields['email'].widget.attrs['placeholder'] = 'e.g. sample@yopmail.com'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'format: +639xxxxxxxxx'
        self.fields['principal_amount'].required = False
        self.fields['principal_amount'].widget.attrs['placeholder'] = "Minimum of Php 10,000.00"
        self.fields['monthly_amortization'].required = False
        self.fields['monthly_amortization'].widget.attrs['placeholder'] = "Minimum of Php 1,000.00"

        if self.instance and self.instance.pk:
            self.fields['first_name'].initial = self.instance.customer_info.first_name
            self.fields['middle_name'].initial = self.instance.customer_info.middle_name
            self.fields['last_name'].initial = self.instance.customer_info.last_name
            self.fields['name_suffix'].initial = self.instance.customer_info.name_suffix
            self.fields['email'].initial = self.instance.customer_info.email
            self.fields['phone_number'].initial = self.instance.customer_info.phone_number
            self.fields['city'].initial = self.instance.customer_info.city
            self.fields['province'].initial = self.instance.customer_info.province

    def clean(self):
        cleaned_data = super().clean()
        loan_type = cleaned_data.get('loan_type')
        principal_amount = cleaned_data.get('principal_amount')
        monthly_amortization = cleaned_data.get('monthly_amortization')
        loan_term = int(cleaned_data.get('loan_term'))

        errors = {}
        if loan_type == 'type_a':
            if not principal_amount:
                errors.update({
                    'principal_amount': 'Principal Amount is required if loan type is Type A.'
                })
            elif principal_amount < Decimal('10000'):
                errors.update({
                    'principal_amount': 'Minimum of PHP 10,000.00'
                })
            if not (3 <= loan_term <= 18):
                errors.update({
                    'loan_term': 'Loan term for Type A should be from 3 months to 18 months with 3 months interval.'
                })
            elif loan_term % 3 != 0:
                errors.update({
                    'loan_term': 'Loan term for Type A should be 3, 6, 9, 12, 15, or 18.'
                })

        if loan_type == 'type_b':
            if not monthly_amortization:
                errors.update({
                    'monthly_amortization': 'monthly_amortization is required if loan_type is Type B.'
                })
            elif monthly_amortization < Decimal('1000'):
                errors.update({
                    'monthly_amortization': 'Minimum of PHP 1,000.00'
                })
            if not (6 <= loan_term <= 18):
                errors.update({
                    'loan_term': 'Loan term for Type A should be from 6 months to 18 months.'
                })

        if errors:
            raise forms.ValidationError(errors)

        if not principal_amount:
            cleaned_data['principal_amount'] = 0
        if not monthly_amortization:
            cleaned_data['monthly_amortization'] = 0

        return cleaned_data

loan_calculator/views.py
import requests
from django.views.generic import UpdateView
from django.shortcuts import redirect
from django.urls import reverse
from rest_framework import generics
from rest_framework import status
from rest_framework.response import Response
from rest_framework.parsers import JSONParser
from rest_framework.parsers import MultiPartParser
from loan_calculator.forms import LoanInquiryForm
from loan_calculator.models import CustomerInfo
from loan_calculator.models import LoanInquiry
from loan_calculator import serializers
from loan_calculator.utils import calculate_monthly_amortization
from loan_calculator.utils import calculate_principal_amount
from loan_calculator.utils import calculate_rate_per_period
from loan_calculator.utils import calculate_total_interest
from loan_calculator.utils import calculate_total_payment
from loan_calculator.utils import get_first_loan_payment_date
from loan_calculator.utils import get_loan_maturity_date


class LoanCalculatorView(UpdateView):
    form_class = LoanInquiryForm
    template_name = 'loan_calculator.html'
    url_name = 'loan_calculator_url'
    model = LoanInquiry

    def get_object(self):
        pk = self.kwargs.get('pk') or None
        loan_inquiry = LoanInquiry.objects.filter(pk=pk).first()
        return loan_inquiry

    def form_valid(self, form):
        url = 'http://%s%s' % (self.request.META['HTTP_HOST'], reverse('loan_calculator_api'))
        form.cleaned_data['phone_number'] = str(form.cleaned_data['phone_number'])
        r = requests.post(url=url, json=form.cleaned_data)
        if r.status_code == 201:
            loan_request_id = r.json()[0].get('id')
            return redirect(reverse(self.url_name, kwargs={'pk': loan_request_id}))
        return redirect(reverse(self.url_name, kwargs=self.kwargs))


class LoanCalculatorAPIView(generics.CreateAPIView):
    parser_classes = [
        JSONParser
    ]
    parser_classes = [
        MultiPartParser,
        JSONParser
    ]
    serializer_class = serializers.LoanCalculatorSerializer

    def create(self, request, *args, **kwargs):

        serializer = self.get_serializer(data=request.data)

        if serializer.is_valid(raise_exception=True):
            loan_inquiry = self.perform_create(serializer)
            return Response(
                LoanInquiry.objects.filter(pk=loan_inquiry.pk).values(
                    'id',
                    'customer_info__first_name',
                    'customer_info__middle_name',
                    'customer_info__last_name',
                    'customer_info__name_suffix',
                    'customer_info__email',
                    'customer_info__phone_number',
                    'customer_info__city',
                    'customer_info__province',
                    'customer_info',
                    'loan_type',
                    'principal_amount',
                    'monthly_amortization',
                    'total_interest',
                    'loan_term',
                    'total_sum_of_payments',
                    'first_loan_payment_date',
                    'loan_maturity_date',
                ),
                status=status.HTTP_201_CREATED,
            )
        else:
            return Response({'error': 'Invalid Input.'}, status=status.HTTP_400_BAD_REQUEST)

    def perform_create(self, serializer):
        first_name = serializer.validated_data.pop('first_name')
        last_name = serializer.validated_data.pop('last_name')
        if 'middle_name' in serializer.validated_data:
            middle_name = serializer.validated_data.pop('middle_name')
        else:
            middle_name = ''

        if 'name_suffix' in serializer.validated_data:
            name_suffix = serializer.validated_data.pop('name_suffix')
        else:
            name_suffix = ''
        email = serializer.validated_data.pop('email')
        phone_number = serializer.validated_data.pop('phone_number')
        city = serializer.validated_data.pop('city')
        province = serializer.validated_data.pop('province')
        loan_type = serializer.validated_data.get('loan_type')
        loan_term = serializer.validated_data.get('loan_term')
        rate_per_period = calculate_rate_per_period()

        if loan_type == 'type_a':
            principal_amount = serializer.validated_data.get('principal_amount')
            monthly_amortization = calculate_monthly_amortization(
                principal_amount=principal_amount,
                rate_per_period=rate_per_period,
                loan_term=loan_term,
            )
        else:
            monthly_amortization = serializer.validated_data.get('monthly_amortization')
            principal_amount = calculate_principal_amount(
                monthly_amortization=monthly_amortization,
                rate_per_period=rate_per_period,
                loan_term=loan_term,
            )

        total_interest = calculate_total_interest(
            principal_amount=principal_amount,
            monthly_amortization=monthly_amortization,
            loan_term=loan_term,
        )

        total_sum_of_payments = calculate_total_payment(
            principal_amount=principal_amount,
            total_interest=total_interest,
        )

        first_loan_payment_date = get_first_loan_payment_date()
        loan_maturity_date = get_loan_maturity_date(
            first_loan_payment_date,
            loan_term,
        )

        customer_info, created = CustomerInfo.objects.get_or_create(
            first_name=first_name,
            last_name=last_name,
            email=email,
            phone_number=phone_number,
            city=city,
            province=province,
            defaults={
                'middle_name': middle_name,
                'name_suffix': name_suffix,
            }
        )

        loan_inquiry = serializer.save(
            customer_info=customer_info,
            principal_amount=principal_amount,
            monthly_amortization=monthly_amortization,
            total_interest=total_interest,
            total_sum_of_payments=total_sum_of_payments,
            first_loan_payment_date=first_loan_payment_date,
            loan_maturity_date=loan_maturity_date,
        )

        return loan_inquiry

    def get(self, request, *args, **kwargs):
        loan_type = self.request.GET.get('loan_type') or None
        qs = LoanInquiry.objects.all()

        if loan_type and loan_type not in ['type_a', 'type_b']:
            return Response(
                'loan type %s is invalid' % (loan_type),
                status=status.HTTP_400_BAD_REQUEST,
            )
        if loan_type:
            qs = qs.filter(loan_type=loan_type)
        return Response(qs.values(
            'customer_info__first_name',
            'customer_info__middle_name',
            'customer_info__last_name',
            'customer_info__name_suffix',
            'customer_info__email',
            'customer_info__phone_number',
            'customer_info__city',
            'customer_info__province',
            'customer_info',
            'loan_type',
            'principal_amount',
            'monthly_amortization',
            'total_interest',
            'loan_term',
            'total_sum_of_payments',
            'first_loan_payment_date',
            'loan_maturity_date',
        ))

loan_calculator/templates/loan_calculator.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Loan Calculator</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script>
    $(document).ready(function(){

      function check_loan_type(){
        var loan_term_field = $("#id_loan_term");
        var loan_term_value = loan_term_field.val()
        loan_term_field.empty()
        value_exists = false
        if($('#id_loan_type').val() == 'type_a'){
          for (var i = 3; i <= 18; i+=3){
            loan_term_field.append($("<option></option>").attr("value", i).text(i))
            if (loan_term_value == i){
              value_exists = true
            }
          }
          $('#div_id_loan_information').removeAttr('hidden')
          $('#div_id_monthly_amortization').attr('hidden', 'hidden')
          $('#div_id_principal_amount').removeAttr('hidden')
        }
        else if ($('#id_loan_type').val() == 'type_b'){
          for (var i = 6; i <= 18; i++){
            loan_term_field.append($("<option></option>").attr("value", i).text(i))
            if (loan_term_value == i){
              value_exists = true
            }
          }
          $('#div_id_loan_information').removeAttr('hidden')
          $('#div_id_monthly_amortization').removeAttr('hidden')
          $('#div_id_principal_amount').attr('hidden', 'hidden')
        }
        else{
          $('#div_id_loan_information').attr('hidden', 'hidden')
        }
        if (value_exists){
          loan_term_field.val(loan_term_value)
        }
      }
      check_loan_type()
      $('#id_loan_type').on('change', function(e){
        check_loan_type()
      })
    })
  </script>
  <style>
    body {
      margin: 0;
    }
    .header {
      overflow: hidden;
      background-color: #2F4F4F;
      color: white;
    }
    #id_first_name, #id_middle_name, #id_last_name, #id_name_suffix {
      width: 25%;
    }
    .form-margin{
      margin-bottom: 1%;
    }
  </style>
</head>
<body>
  <header>
    <div class='header'>
      <div style="text-align: center;">
        <h2>Loan Calculator</h2>
      </div>
    </div>
  </header>
  <div class='container' style='margin-top: 1%;'>
    <form method='POST' class="form-horizontal"> {% csrf_token %}
      <div class='form-group'>

        <div class='row form-margin'>
          <div class='col-md-3' style="text-align: right; margin-top: 0.5%;">
            <label>Full Name:</label>
          </div>
          <div class='col-md-9'>
            <div class='input-group' style="width: 100%;">
              {{ form.last_name }}
              {{ form.first_name }}
              {{ form.middle_name }}
              {{ form.name_suffix }}
            </div>
          </div>
        </div>

        <div class='row form-margin'>
          <div class='col-md-3' style="text-align: right; margin-top: 0.5%;">
            <label for="id_loan_type">{{ form.email.label }}:</label>
          </div>
          <div class='col-md-9'>
            {{ form.email }}
            {{ form.email.errors }}
          </div>
        </div>

        <div class='row form-margin'>
          <div class='col-md-3' style="text-align: right; margin-top: 0.5%;">
            <label for="phone_number">{{ form.phone_number.label }}:</label>
          </div>
          <div class='col-md-9'>
            {{ form.phone_number }}
            {{ form.phone_number.errors }}
          </div>
        </div>

        <div class='row form-margin'>
          <div class='col-md-3' style="text-align: right; margin-top: 0.5%;">
            <label for="city">{{ form.city.label }}:</label>
          </div>
          <div class='col-md-9'>
            {{ form.city }}
            {{ form.city.errors }}
          </div>
        </div>

        <div class='row form-margin'>
          <div class='col-md-3' style="text-align: right; margin-top: 0.5%;">
            <label for="province">{{ form.province.label }}:</label>
          </div>
          <div class='col-md-9'>
            {{ form.province }}
            {{ form.province.errors }}
          </div>
        </div>

        <div class='row form-margin'>
          <div class='col-md-3' style="text-align: right; margin-top: 0.5%;">
            <label for="loan_type">{{ form.loan_type.label }}:</label>
          </div>
          <div class='col-md-9'>
            {{ form.loan_type }}
            {{ form.loan_type.errors }}
          </div>
        </div>
        <div id='div_id_loan_information'>
          <div class='row form-margin' id='div_id_principal_amount'>
            <div class='col-md-3' style="text-align: right; margin-top: 0.5%;">
              <label for="principal_amount">{{ form.principal_amount.label }}:</label>
            </div>
            <div class='col-md-9'>
              {{ form.principal_amount }}
              {{ form.principal_amount.errors }}
            </div>
          </div>

          <div class='row form-margin' id='div_id_monthly_amortization'>
            <div class='col-md-3' style="text-align: right; margin-top: 0.5%;">
              <label for="monthly_amortization">{{ form.monthly_amortization.label }}:</label>
            </div>
            <div class='col-md-9'>
              {{ form.monthly_amortization }}
              {{ form.monthly_amortization.errors }}
            </div>
          </div>

          <div class='row form-margin'>
            <div class='col-md-3' style="text-align: right; margin-top: 0.5%;">
              <label for="loan_term">{{ form.loan_term.label }}:</label>

            </div>
            <div class='col-md-9'>
              {{ form.loan_term }}
              {{ form.loan_term.errors }}
            </div>
          </div>
        </div>
        <button type="submit" class="btn btn-primary pull-right">Calculate</button>
        <a type="button" class="btn btn-default pull-right" href="{% url 'loan_calculator_url' %}" style='margin-right: 1%;'>New</a>
      </div>
    </form>
    {% if object %}
      <div class='row'>
        <div class='col-md-3'></div>
        <div class='col-md-6'>
          <table class='table table-striped'>
            <thead>
              <th>Description</th>
              <th>Details</th>
            </thead>
            <tbody>
              <tr>
                <th>Principal Amount</th>
                <td>{{ object.principal_amount }}</td>
              </tr>
              <tr>
                <th>Monthly Amortization</th>
                <td>{{ object.monthly_amortization }}</td>
              </tr>
              <tr>
                <th>Total Interest</th>
                <td>{{ object.total_interest }}</td>
              </tr>
              <tr>
                <th>Loan Term</th>
                <td>{{ object.loan_term }}</td>
              </tr>
              <tr>
                <th>Total Sum of Payments upon loan maturity</th>
                <td>{{ object.total_sum_of_payments }}</td>
              </tr>
              <tr>
                <th>First Loan Payment Date</th>
                <td>{{ object.first_loan_payment_date }}</td>
              </tr>
              <tr>
                <th>Loan Maturity Date</th>
                <td>{{ object.loan_maturity_date }}</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class='col-md-3'></div>
      </div>
    {% endif %}
  </div>
</body>
</html>